### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by solo111** [dashpay/sentinel#122]
From this day it doesn't work with error
```
Wed Nov 22 16:46:30 UTC 2023 Traceback (most recent call last): File "/home/ubuntu/.dashcore/sentinel/
bin/sentinel.py", line 230, in <module> main() File "/home/ubuntu/.dashcore/sentinel/bin/sentinel.py",
 line 176, in main attempt_superblock_creation(dashd) File "/home/ubuntu/.dashcore/sentinel/bin/sentin
el.py", line 66, in attempt_superblock_creation proposal_quorum=dashd.governance_quorum(), File "/home
/ubuntu/.dashcore/sentinel/lib/dashd.py", line 97, in governance_quorum hpmn_weight = masternode_count
["detailed"]["hpmn"]["enabled"] Dockerfile LICENSE README.md bin database lib requirements.txt 
sentinel-cron.log sentinel.conf share test venv 4 KeyError: 'hpmn'
```
Do i need Sentinel to work a masternode?

**Comment by PastaPastaPasta** [comment]
Please provide all details of your system / stack when reporting any issues. This includes, dash core version, OS, OS version, etc. In this case, I think you simply need to read the v20 release notes https://github.com/dashpay/dash/blob/v20.0.0/doc/release-notes.md

Specifically:
https://github.com/dashpay/dash/blob/v20.0.0/doc/release-notes.md#sentinel-deprecation

**Comment by solo111** [comment]
Thanx! I have just read the Release Notes for 20.0 so excuse me for my inattentiveness. Sentinel is depricated from v20.0.0
