### ISSUE TITLE
Use the RPC connect IP from dash.conf

### ISSUE THREAD

**Issue by osyed** [dashpay/sentinel#3]
Sentinel is using only 127.0.0.1 when trying to connect to dashd. It needs to also use the 'rpcconnect' value if it was set in dash.conf.

Just a few lines needs to be changed in dash_config.py:

        # Changed the following line
        #match = re.findall(r'rpc(user|password|port)=(.*?)$', data, re.MULTILINE)
        match = re.findall(r'rpc(user|password|port|connect)=(.*?)$', data, re.MULTILINE)

        # Added the following before
        #    return creds
        # set the host from config file
        if ('connect' in creds):
            creds[u'host'] = creds[u'connect']

**Comment by nmarley** [comment]
This has been obsoleted by #91
