### ISSUE TITLE
Sentinel can't connect if rpcuser/rpcpassword string has special characters

### ISSUE THREAD

**Issue by UdjinM6** [dashpay/sentinel#4]
see https://github.com/dashpay/dash/issues/1323

**Comment by jhodges10** [comment]
Had this issue in the past when using a randomly generated password and couldn't figure out why it wasn't working. Good to see it being addressed.

**Comment by thephez** [comment]
Closing this issue since Dash Core v20 integrated all Sentinel functionality and [rendered Sentinel obsolete](https://github.com/dashpay/dash/blob/v20.0.0/doc/release-notes.md#sentinel-deprecation).
