### ISSUE TITLE
For dashd v0.16.0.0-RC1 getinfo RPC has been deprecated, but sentinel still uses it

### ISSUE THREAD

**Issue by kxcd** [dashpay/sentinel#68]
At least that is how it seems to me.  Two locations where getinfo is referenced and I see it in my sentinel output when I run the tests.  I am using the develop branch.
https://github.com/dashpay/sentinel/blob/develop/test/integration/test_jsonrpc.py#L34
https://github.com/dashpay/sentinel/blob/develop/README.md
Sentinel _seems_ to still work with this issue, TBH I don't really know, I do know the tests fail.

![](https://cdn.discordapp.com/attachments/480989645614743562/721292848259006564/unknown.png)

**Comment by nmarley** [comment]
Thanks for reporting. This is only used in the "integration test", which really isn't in scope for what the code base does (this external JSONRPC connection test could be done upon startup, for example -- a test isn't needed). I'll open a PR to remove the test.

**Comment by nmarley** [comment]
Fixed in #69.
